from PIL import Image,ImageOps
import os,sys,bitplanelib,math

from shared import *

import generate_tiles

sprite_names = get_sprite_names()

mirror_sprites = get_mirror_sprites()



possible_hw_sprites = set()

# uncomment to disable hw sprites completely
#possible_hw_sprites = set()


generated_message = "* generated by convert_graphics.py\n"
dump_it = True



if dump_it:
    if not os.path.exists(dump_dir):
        os.mkdir(dump_dir)
        with open(os.path.join(dump_dir,".gitignore"),"w") as f:
            f.write("*")


def dump_asm_bytes(*args,**kwargs):
    bitplanelib.dump_asm_bytes(*args,**kwargs,mit_format=True)


def ensure_empty(d):
    if d.exists():
        for f in os.listdir(d):
            os.remove(os.path.join(d,f))
    else:
        d.mkdir(parents=True)

def is_pre_mirrored(prefix,context):
    return False

    pc = sprites_per_level.get(prefix)
    if not pc:
        # not listed: pre-mirror to avoid issues
        return True
    pre_mirror = pc["pre_mirror"]
    if pre_mirror is None:
        # never pre-mirror
        return False
    if pre_mirror == True:
        # always pre-mirror
        return True
    # pre-mirror only in some levels
    return context in pre_mirror

def is_in_level(prefix,context):
    return True

    pc = sprites_per_level.get(prefix)
    if not pc:
        # not listed: in all levels & contextes
        return True
    levels = pc["levels"]
    if not levels:
        # also included in all levels
        return True
    if context is None:
        # context none: global, pc not found or : include
        return not levels
    # included only if context defined and matches
    return not levels or context in levels

def dump_bob_layer(sprite_table,f,relative_root=None,context=None):
    if relative_root:
        f.write(f"{relative_root}:\n")
    for i,tile_entry in enumerate(sprite_table):
        f.write("\t.long\t")
        if i not in possible_hw_sprites and any(tile_entry):
            prefix = sprite_names.get(i,"bob")
            if is_in_level(prefix,context):
                f.write(f"{prefix}_{i:02x}")
                if relative_root:
                    f.write(f"-{relative_root}")
            else:
                f.write("0")
        else:
            f.write("0")
        f.write("\n")


    for i,tile_entry in enumerate(sprite_table):
        if i not in possible_hw_sprites and any(tile_entry):
            prefix = sprite_names.get(i,"bob")
            if is_in_level(prefix,context):
                f.write(f"{prefix}_{i:02x}:\n")
                for j,t in enumerate(tile_entry):
                    f.write("\t.long\t")
                    if t:
                        f.write(f"{prefix}_{i:02x}_{j:02x}")
                        if relative_root:
                            f.write(f"-{relative_root}")
                    else:
                        f.write("0")
                    f.write("\n")

    needed_bob_bitplanes = set()

    for i,tile_entry in enumerate(sprite_table):
        if i not in possible_hw_sprites and any(tile_entry):
            prefix = sprite_names.get(i,"bob")
            if is_in_level(prefix,context):
                for j,t in enumerate(tile_entry):
                    if t:
                        name = f"{prefix}_{i:02x}_{j:02x}"

                        f.write(f"{name}:\n")
                        height = 0

                        offset = 0
                        for orientation,_ in plane_orientations:
                            if orientation in t:
                                width = t[orientation]["width"]
                                height = t[orientation]["height"]
                                offset = t[orientation]["y_start"]
                                break
                        else:
                            raise Exception(f"height not found for {name}!!")
                        nonzero_written = False
                        for orientation,_ in plane_orientations:
                            # loop for this, this sucks
                            if orientation == "standard":
                                f.write("* orientation={}\n".format(orientation))
                                active_planes = 0
                                bitplanes = t[orientation]["bitplanes"]

                                for j,bitplane_id in enumerate(bitplanes):
                                    if bitplane_id:
                                        active_planes |= 1<<j
                                bitplane_info = f"\t.word\t{height},{width},{offset},0x{active_planes:x}  | height,width,offset,active_planes\n"
                                f.write(bitplane_info)
                                for bitplane_id in bitplanes:
                                    f.write("\t.long\t")
                                    if bitplane_id:
                                        nonzero_written = True
                                        bob_bitplane_ptr = f"bob_plane_{bitplane_id:02d}"
                                        needed_bob_bitplanes.add(bitplane_id)
                                        f.write(bob_bitplane_ptr)
                                        if relative_root:
                                            f.write(f"-{relative_root}")
                                    else:
                                        f.write("0")
                                    f.write("\n")

                        if nonzero_written and is_pre_mirrored(prefix,context):
                            # tell the game engine that it has to mirror the bitplanes
                            # at start/file load and put them here
                            # (except if tile has 0 data because it's blank)

                            f.write("* mirrored bitplanes pointers (inc. mask) go here\n")
                            for _ in bitplanes:
                                f.write(f"\t.long\t-1\n")
                        else:
                            # tell the game engine that it has to mirror in-place
                            f.write("\t.word\t-2    | bitplanes above will be mirrored in-place\n\n")

    if not relative_root:
        f.write("end_tables:\n\t.section\t.datachip\n")

    for k,v in bob_plane_cache.items():
        if v in needed_bob_bitplanes:
            f.write(f"""
\t.word\t0    | plane {v:02d} orientation
bob_plane_{v:02d}:""")
            dump_asm_bytes(k,f)

def load_tileset(image_name,palette_index,width,height,tileset_name,dumpdir,
dump=False,name_dict=None,cluts=None,tile_number=0,is_bob=False):

##    if isinstance(image_name,str):
##        full_image_path = os.path.join(this_dir,os.path.pardir,"sheets",
##                            tile_type,image_name)
##        tiles_1 = Image.open(full_image_path)
##    else:
    tiles_1 = image_name
    nb_rows = tiles_1.size[1] // height
    nb_cols = tiles_1.size[0] // width


    tileset_1 = []

    if dump:
        dump_subdir = dumpdir / tileset_name
        if palette_index == 0 and tile_number == 0:
            ensure_empty(dump_subdir)

    palette = set()

    for j in range(nb_rows):
        for i in range(nb_cols):

            if cluts is not None and (tile_number not in cluts or palette_index not in cluts[tile_number]):
                # no clut declared for that tile
                tileset_1.append(None)
            else:

                img = Image.new("RGB",(width,height))
                img.paste(tiles_1,(-i*width,-j*height))


                # only consider colors of used tiles
                palette.update(set(bitplanelib.palette_extract(img)))


                tileset_1.append(img)
                # dump tiles
                if not is_bob and dump:
                    img = ImageOps.scale(img,5,resample=Image.Resampling.NEAREST)
                    if name_dict:
                        name = name_dict.get(tile_number,"unknown")
                    else:
                        name = "unknown"

                    img.save(os.path.join(dump_subdir,f"{name}_{tile_number:02x}_{palette_index:02x}.png"))
            tile_number += 1

    if is_bob:

        # rework & dump grouped / non grouped sprites
        # rework tiles which are grouped
        for tile_number,wtile in enumerate(tileset_1):

            if wtile:
                if tile_number in group_sprite_pairs:
                    # change wtile, fetch code +1
                    other_tile_index = tile_number+1
                    other_tile = tileset_1[other_tile_index]
                    if not other_tile:
                        raise Exception(f"pair: 0x{tile_number:02x} ok but other tile index 0x{other_tile_index:02x} not found")
                    new_tile = Image.new("RGB",(wtile.size[0]*2,wtile.size[1]))

                    new_tile.paste(wtile)

                    new_tile.paste(other_tile,(wtile.size[0],0))
                    tileset_1[tile_number] = new_tile
                    tileset_1[other_tile_index] = None  # discatd
                    wtile = new_tile

                elif tile_number in group_sprite_triplets:
                    # change wtile, fetch code +1
                    central_tile_index = tile_number+1
                    central_tile = tileset_1[central_tile_index]
                    right_tile_index = central_tile_index+1
                    right_tile = tileset_1[right_tile_index]
                    if not central_tile:
                        raise Exception(f"triplet: central tile index 0x{central_tile_index:02x} not found")
                    if not right_tile:
                        raise Exception(f"triplet: right tile index 0x{right_tile_index:02x} not found")
                    new_tile = Image.new("RGB",(wtile.size[0]*3,wtile.size[1]))

                    new_tile.paste(wtile)

                    new_tile.paste(central_tile,(wtile.size[0],0))
                    new_tile.paste(right_tile,(wtile.size[0]*2,0))
                    tileset_1[tile_number] = new_tile
                    tileset_1[central_tile_index] = None  # discard
                    tileset_1[right_tile_index] = None  # discard
                    wtile = new_tile

                elif tile_number in group_sprite_quadruplets:
                    # change wtile, fetch code +1
                    central_tile_index = tile_number+1
                    central_tile_1 = tileset_1[central_tile_index]
                    central_tile_2 = tileset_1[central_tile_index+1]
                    right_tile_index = central_tile_index+2
                    right_tile = tileset_1[right_tile_index]
                    if not central_tile_1:
                        raise Exception(f"triplet: central tile index 0x{central_tile_index:02x} not found")
                    if not central_tile_2:
                        raise Exception(f"triplet: central tile index 0x{central_tile_index+1:02x} not found")
                    if not right_tile:
                        raise Exception(f"triplet: right tile index 0x{right_tile_index:02x} not found")
                    new_tile = Image.new("RGB",(wtile.size[0]*4,wtile.size[1]))

                    new_tile.paste(wtile)

                    new_tile.paste(central_tile_1,(wtile.size[0],0))
                    new_tile.paste(central_tile_2,(wtile.size[0]*2,0))
                    new_tile.paste(right_tile,(wtile.size[0]*3,0))
                    tileset_1[tile_number] = new_tile
                    tileset_1[central_tile_index] = None  # discard
                    tileset_1[central_tile_index+1] = None  # discard
                    tileset_1[right_tile_index] = None  # discard
                    wtile = new_tile

            if dump_it and wtile:
                img = ImageOps.scale(wtile,5,resample=Image.Resampling.NEAREST)
                if sprite_names:
                    name = sprite_names.get(tile_number,"unknown")
                else:
                    name = "unknown"

                img.save(os.path.join(dump_subdir,f"{name}_{tile_number:02x}_{palette_index:02x}.png"))



    return sorted(set(palette)),tileset_1

all_tile_cluts = False



sprite_cluts = {}
fg_tile_cluts = {}

total_nb_colors = 64

read_used_tiles("fg_used_tiles",fg_tile_cluts,FG_NB_TILES,FG_NB_CLUTS)

read_used_tiles("used_sprites",sprite_cluts,SPRITE_NB_TILES,SPRITE_NB_CLUTS)

# add "used" property for other sprite
for g in group_sprite_pairs:
    sc = sprite_cluts.get(g)
    if sc:
        sprite_cluts[g+1] = sc


# now gather all cluts used by letter/digit tiles, logging probably
# missed some
# some tiles are hard to display... We know they are there, we force them
# instead of trying to trigger them by playing to death :)

alphanum_tile_codes = list(range(0,10)) + list(range(ord('A'),ord('Z')+1)) + list(range(ord('a'),ord('z')+1))+ list(range(ord('0'),ord('9')+1))
used_cluts = set()
for atc in alphanum_tile_codes:
    cluts = fg_tile_cluts.get(atc)
    if cluts:
        used_cluts.update(cluts)
# now set cluts for all alphanum tiles
for atc in alphanum_tile_codes:
    fg_tile_cluts[atc] = sorted(used_cluts)


plane_orientations = [("standard",lambda x:x),
("flip",ImageOps.flip),
("mirror",ImageOps.mirror),
("flip_mirror",lambda x:ImageOps.flip(ImageOps.mirror(x)))]




def read_tileset(img_set_list,palette,plane_orientation_flags,cache,is_bob,nb_cluts,mask_color,next_cache_id = 1):
    nb_planes = int(math.log2(len(palette)))

    tile_table = []
    for n,img_set in enumerate(img_set_list):
        tile_entry = []
        for i,tile in enumerate(img_set):
            entry = dict()
            if tile:

                for b,(plane_name,plane_func) in zip(plane_orientation_flags,plane_orientations):
                    bitplane_sprite_data = None
                    if b:

                        actual_nb_planes = nb_planes

                        # most sprites aren't mirrored. Save a lot of memory!
                        if plane_func == ImageOps.mirror and i not in mirror_sprites:
                            continue

                        wtile = plane_func(tile)

                        if is_bob:
                            actual_nb_planes += 1


                            # only 4 planes + mask => 5 planes
                            orig_wtile = wtile
                            y_start,wtile = bitplanelib.autocrop_y(wtile,mask_color=magenta)
                            height = wtile.size[1]
                            width = wtile.size[0]//8 + 2
                            bitplane_data = bitplanelib.palette_image2raw(wtile,None,palette,generate_mask=True,mask_color=mask_color)
                            # add sprite data if eligible: player frame, not mirrored

##                            if i in possible_hw_sprites:
##                                # using original, uncropped bitplane data
##                                bitplane_sprite_data = bitplanelib.palette_image2attached_sprites(orig_wtile,None,palette,
##                                sprite_fmode=2,with_control_words=True)
##                                # void the blitter data
##                                bitplane_data = b''
                        else:
                            # 4 planes, no mask
                            height = 8
                            width = 1
                            y_start = 0
                            bitplane_data = bitplanelib.palette_image2raw(wtile,None,palette,mask_color=mask_color)

                        plane_size = len(bitplane_data) // actual_nb_planes
                        bitplane_plane_ids = []
                        for j in range(actual_nb_planes):
                            offset = j*plane_size
                            bitplane = bitplane_data[offset:offset+plane_size]

                            cache_id = cache.get(bitplane)
                            if cache_id is not None:
                                bitplane_plane_ids.append(cache_id)
                            else:
                                if any(bitplane):
                                    cache[bitplane] = next_cache_id
                                    bitplane_plane_ids.append(next_cache_id)
                                    next_cache_id += 1
                                else:
                                    bitplane_plane_ids.append(0)  # blank
                        entry[plane_name] = {"width":width,"height":height,"y_start":y_start,"bitplanes":bitplane_plane_ids}
                        if bitplane_sprite_data:
                            entry[plane_name]["sprdat"] = bitplane_sprite_data

            tile_entry.append(entry)

        tile_table.append(tile_entry)

    new_tile_table = [[[] for _ in range(nb_cluts)] for _ in range(len(tile_table[0]))]

    # reorder/transpose. We have 16 * 256 we need 256 * 16
    for i,u in enumerate(tile_table):
        for j,v in enumerate(u):
            new_tile_table[j][i] = v

    return new_tile_table,next_cache_id


def dump_tile_layer(tile_table,prefix,relative_root=None):
    item_decl = "\t.long\t"
    if relative_root:
        f.write(f"{relative_root}:\n")
    for i,tile_entry in enumerate(tile_table):
        f.write(item_decl)
        if tile_entry and any(tile_entry):
            f.write(f"{prefix}tile_{i:02x}")
            if relative_root:
                f.write(f"-{relative_root}")
        else:
            f.write("0")
        f.write("\n")

    for i,tile_entry in enumerate(tile_table):
        if tile_entry and any(tile_entry):
            rr = f"{prefix}tile_{i:02x}"
            f.write(f"{rr}:\n")
            for j,t in enumerate(tile_entry):
                f.write(item_decl)
                if t:
                    f.write(f"{prefix}tile_{i:02x}_{j:02x}")
                    if relative_root:
                        f.write(f"-{relative_root}")
                else:
                    f.write("0")
                f.write("\n")


    for i,tile_entry in enumerate(tile_table):
        if tile_entry and any(tile_entry):
            for j,t in enumerate(tile_entry):
                if t:
                    name = f"{prefix}tile_{i:02x}_{j:02x}"

                    f.write(f"{name}:\n")
                    for orientation,_ in plane_orientations:
                        f.write("* orientation={}\n".format(orientation))
                        if orientation in t:
                            data = t[orientation]
                            for bitplane_id in data["bitplanes"]:
                                f.write(item_decl)
                                if bitplane_id:
                                    f.write(f"{prefix}tile_plane_{bitplane_id:02d}")
                                    if relative_root:
                                        f.write(f"-{relative_root}")
                                else:
                                    f.write("0")
                                f.write("\n")
                            if len(t)==1:
                                # optim: only standard
                                break
                        else:
                            for _ in range(nb_planes):
                                f.write(f"{item_decl}0\n")
    return i+1


def apply_color_replacement(sprite_set_list,quantized):
    """ change colors for list of tilesets (tiles, sprites)
    quantized: RGB => RGB color replacement dictionary
    """

    for sset in sprite_set_list:
        for tile in sset:
            if tile:
                bitplanelib.replace_color_from_dict(tile,quantized)

def quantize_palette(rgb_tuples,img_type,nb_quantize,transparent=None,dump_it=False):
    rgb_configs = set(rgb_tuples)

    nb_target_colors = nb_quantize
    if transparent:
        rgb_configs.remove(transparent)
        # remove black, white, we don't want it quantized
        immutable_colors = (transparent,black)
    else:
        immutable_colors = (black,)

    for c in immutable_colors:
        rgb_configs.discard(c)
        nb_quantize -= 1

    dump_graphics = False
    # now compose an image with the colors
    clut_img = Image.new("RGB",(len(rgb_configs),1))
    for i,rgb in enumerate(rgb_configs):
        #rgb_value = (rgb[0]<<16)+(rgb[1]<<8)+rgb[2]
        clut_img.putpixel((i,0),rgb)

    reduced_colors_clut_img = clut_img.quantize(colors=nb_quantize,dither=0).convert('RGB')

    # get the reduced palette
    reduced_palette = [reduced_colors_clut_img.getpixel((i,0)) for i,_ in enumerate(rgb_configs)]
    # apply rounding now, else possible color duplicates, which would be a pity
    reduced_palette = bitplanelib.palette_round(reduced_palette,0xF0)

    # now create a dictionary by associating the original & reduced colors
    rval = dict(zip(rgb_configs,reduced_palette))

    # add black & white & transparent back
    for c in immutable_colors:
        rval[c] = c


    if dump_it:  # debug it, create 2 rows, 1 non-quantized, and 1 quantized, separated by bloack
        s = clut_img.size
        ns = (s[0]*30,s[1]*30)
        clut_img = clut_img.resize(ns,resample=0)
        whole_image = Image.new("RGB",(clut_img.size[0],clut_img.size[1]*3))
        whole_image.paste(clut_img,(0,0))
        reduced_colors_clut_img = reduced_colors_clut_img.resize(ns,resample=0)
        whole_image.paste(reduced_colors_clut_img,(0,clut_img.size[1]*2))
        whole_image.save(dump_dir / "{}_colors.png".format(img_type))

    result_nb = len(set(reduced_palette))
    if nb_quantize < result_nb:
        raise Exception(f"quantize: {img_type}: {nb_quantize} expected, found {result_nb}")
    # return it
    return rval



if dump_it:
    if not all_tile_cluts:
        with open(dump_dir / "used_sprites.json","w") as f:
            sprite_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in sprite_cluts.items() if v}
            json.dump(sprite_cluts_dict,f,indent=2)
        with open(dump_dir / "used_fg_tiles.json","w") as f:
            fg_tile_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in fg_tile_cluts.items() if v}
            json.dump(fg_tile_cluts_dict,f,indent=2)





sprite_sheet_dict = {i:img for i,img in enumerate(generate_tiles.doit_sprites_16x16())}
fg_tile_sheet_dict = {i:img for i,img in enumerate(generate_tiles.doit_tiles_8x8())}

###############
# foreground
# not so simple as we need to separate tiles for better colors
###############
fg_tile_upper_palette = set()  # mostly alphanum + title
fg_tile_upper_set_list = []


for i,tsd in fg_tile_sheet_dict.items():
    _,tile_set = load_tileset(tsd,i,8,8,"fg_tiles",dump_dir,dump=dump_it,
    cluts=fg_tile_cluts,
    name_dict=None)

    # we need to separate the palettes for OSD because 1) there are too many of them and quantize sucks
    # and 2) the colors of the weapons in the panel is dynamic

    upper_tile_set = [None] * len(tile_set)
    lower_tile_set = [None] * len(tile_set)
    for j,tile in enumerate(tile_set):
        tp = set()
        if tile:
            tp = set(bitplanelib.palette_extract(tile))
            fg_tile_upper_palette.update(tp)
            upper_tile_set[j] = tile

    fg_tile_upper_set_list.append(upper_tile_set)

### we'll quantize manually, 21 FG colors => 18
##fg_replacement_dict = {(174,157,112):(188,157,112),
##(45,31,0):black,
##(188,174,174):(174,174,174),
##}
##apply_color_replacement(fg_tile_upper_set_list,fg_replacement_dict)

### recompute new fg palette
##fg_tile_upper_palette = set()
##
##for tile_set in fg_tile_upper_set_list:
##    for j,tile in enumerate(tile_set):
##        tp = set()
##        if tile:
##            tp = set(bitplanelib.palette_extract(tile))
##            fg_tile_upper_palette.update(tp)

# then lazy me let's quantize 18=>16
fg_nb_colors = 16
if len(fg_tile_upper_palette)>fg_nb_colors:
    print(f"Too many colors in fg upper tiles ({len(fg_tile_upper_palette)}), quantizing")
    bitplanelib.palette_dump(fg_tile_upper_palette,dump_dir / "fg_tile_palette_orig.png",pformat=bitplanelib.PALETTE_FORMAT_PNG)

    for attempt_nb_colors in [fg_nb_colors+3,fg_nb_colors+2,fg_nb_colors+1,fg_nb_colors]:
        fg_replacement_dict = quantize_palette(fg_tile_upper_palette,"foreground_upper_tiles",attempt_nb_colors,transparent=magenta,dump_it=dump_it)
        new_fg_tile_upper_palette = sorted(set(fg_replacement_dict.values()))
        if len(new_fg_tile_upper_palette)<=fg_nb_colors:
            print(f"Quantization achieved {len(new_fg_tile_upper_palette)} colors with start colors = {attempt_nb_colors}")
            fg_tile_upper_palette = new_fg_tile_upper_palette
            break
    else:
        raise Exception("quantize error")  # not really possible since we try 32 as last chance!
    apply_color_replacement(fg_tile_upper_set_list,fg_replacement_dict)
    fg_tile_upper_palette = sorted(set(fg_replacement_dict.values()))
    bitplanelib.palette_dump(fg_tile_upper_palette,dump_dir / "fg_tile_palette_after.png",pformat=bitplanelib.PALETTE_FORMAT_PNG)
else:
    fg_tile_upper_palette = sorted(fg_tile_upper_palette)

# magenta first
fg_tile_upper_palette.remove(magenta)
fg_tile_upper_palette.insert(0,magenta)




print(f"Used fg tile colors: {len(fg_tile_upper_palette)}")

bitplanelib
# pad to 16 colors
for p in [fg_tile_upper_palette]:
    p += (16-len(p)) * [(0x10,0x20,0x30)]

###############
# background
###############

bg_tile_sheet_dict = {i:img for i,img in enumerate(generate_tiles.doit_tiles_16x16())}

bg_tile_cluts = {}
read_used_tiles("bg_used_tiles",bg_tile_cluts,BG_NB_TILES,BG_NB_CLUTS)

bg_tile_palette = set()
bg_tile_set_list = []


for i,tsd in bg_tile_sheet_dict.items():
    tp,tile_set = load_tileset(tsd,i,16,16,"bg_tiles",dump_dir,dump=dump_it,
    cluts=bg_tile_cluts,
    name_dict=None)
    for j,tile in enumerate(tile_set):
        if tile:
            # images are mirrored & flipped, fix this here
            tile = ImageOps.mirror(tile)
            tile = ImageOps.flip(tile)
            tile_set[j] = tile

    bg_tile_set_list.append(tile_set)
    bg_tile_palette.update(tp)

sprite_set_list = []
for i,tsd in sprite_sheet_dict.items():
    tp,tile_set = load_tileset(tsd,i,16,16,"sprites",dump_dir,dump=dump_it,
    cluts=sprite_cluts,
    name_dict=get_sprite_names(),
    is_bob=True)
    sprite_set_list.append(tile_set)
    bg_tile_palette.update(tp)




##if len(bg_tile_palette)>total_nb_colors:
##    print(f"Too many colors in sprite tiles ({len(sprite_palette)}), quantizing")
##    # if we specify 32 right away, the algorithm can provide less colors than 32, wasting entries
##    # by attempting to quantize with higher values, we guarantee not to waste colors
##    for attempt_nb_colors in [total_nb_colors+3,total_nb_colors+2,total_nb_colors+1,total_nb_colors]:
##        sprite_replacement_dict = quantize_palette(bg_tile_palette,"sprite_tiles",attempt_nb_colors,dump_it=dump_it)
##        new_sprite_palette = sorted(set(sprite_replacement_dict.values()))
##        if len(new_sprite_palette)<=total_nb_colors:
##            print(f"Quantization achieved {len(new_sprite_palette)} colors with start colors = {attempt_nb_colors}")
##            bg_tile_palette = new_sprite_palette
##            break
##    else:
##        raise Exception("quantize error")  # not really possible since we try 32 as last chance!
##
##    apply_color_replacement(bg_tile_set_list,sprite_replacement_dict)
##    apply_color_replacement(sprite_set_list,sprite_replacement_dict)
##else:

# no need to quantize on that game, 64 colors does it perfectly yay
# but to optimize bitplane copy, we can put some colors in strategic power of 2 locations
# so 1-bitplane images are blitted faster

# pad if needed
bg_tile_palette.remove(magenta)
bg_tile_palette = sorted(bg_tile_palette)



print(f"Used bg tile colors: {len(bg_tile_palette)}")
bg_tile_palette += (total_nb_colors-len(bg_tile_palette)) * [(0x10,0x20,0x30)]

if dump_it:
    if not all_tile_cluts:
        with open(dump_dir / "used_sprites.json","w") as f:
            sprite_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in sprite_cluts.items() if v}
            json.dump(sprite_cluts_dict,f,indent=2)
        with open(dump_dir / "used_fg_tiles.json","w") as f:
            fg_tile_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in fg_tile_cluts.items() if v}
            json.dump(fg_tile_cluts_dict,f,indent=2)
        dump_dir.mkdir(exist_ok=True)
        with open(dump_dir / "used_bg_tiles.json","w") as f:
            bg_tile_cluts_dict = {hex(k):[hex(x) for x in v] for k,v in bg_tile_cluts.items() if v}
            json.dump(bg_tile_cluts_dict,f,indent=2)

bg_tile_plane_cache = {}

bg_tile_table,_ = read_tileset(bg_tile_set_list,bg_tile_palette,[True,False,False,False],cache=bg_tile_plane_cache,
is_bob=False, nb_cluts=BG_NB_CLUTS, mask_color=black)



###############
# sprites
###############




tile_plane_cache = {}
bob_plane_cache = {}
fg_tile_upper_table,_ = read_tileset(fg_tile_upper_set_list,fg_tile_upper_palette,[True,False,False,False],cache=tile_plane_cache, is_bob=False, nb_cluts=FG_NB_CLUTS, mask_color=magenta)


sprite_table,_ = read_tileset(sprite_set_list,bg_tile_palette,[True,False,False,False],cache=bob_plane_cache, is_bob=True, mask_color=magenta, nb_cluts=SPRITE_NB_CLUTS)



with open(src_dir / "palette.68k","w") as f:
    f.write(generated_message)
    f.write("fg_tile_palette:\n")
    bitplanelib.palette_dump(fg_tile_upper_palette,f,bitplanelib.PALETTE_FORMAT_ASMGNU)
    f.write("bg_tile_palette:\n")
    bitplanelib.palette_dump(bg_tile_palette,f,bitplanelib.PALETTE_FORMAT_ASMGNU)

BLOCK_DISPLAY_MASK = 1<<14
DO_DISPLAY_MASK = 1

def gen_codes(i):
    im = (i<<1)
    return im | DO_DISPLAY_MASK,(0x800 + im) | DO_DISPLAY_MASK

gs_array = [0]*SPRITE_NB_TILES
for i in group_sprite_pairs:
    gs_array[i],gs_array[i+1] = gen_codes(i)

for i in group_sprite_triplets:
    gs_array[i],gs_array[i+2] = gen_codes(i)
    gs_array[i+1] = BLOCK_DISPLAY_MASK    # never display alone!
for i in group_sprite_quadruplets:
    gs_array[i],gs_array[i+3] = gen_codes(i)
    gs_array[i+1] = BLOCK_DISPLAY_MASK    # never display alone!
    gs_array[i+2] = BLOCK_DISPLAY_MASK    # never display alone!

used_sprite_codes = set(sprite_cluts) | {i for i,g in enumerate(gs_array) if g}
unused_sprite_codes = set(range(0,0x300))-used_sprite_codes
# it's normal that some sprite codes aren't used at all, see https://tcrf.net/Commando_(Arcade,_Capcom)
#print("Unused sprite codes: {}".format(",".join(sorted(f"0x{x:03x}" for x in unused_sprite_codes))))

with open(src_dir / "sprite_groups.68k","w") as f:
    f.write(generated_message)
    f.write("* see amiga.68k display_one_bob routine to know how this works\n")

    bitplanelib.dump_asm_bytes(gs_array,f,mit_format=True,size=2)

##with open(src_dir / "object_type_table.68k","w") as f:
##    f.write(generated_message)
##    f.write("* see amiga.68k really_update_sprites routine to know how this works\n")
##
##    bitplanelib.dump_asm_bytes(object_type_table,f,mit_format=True,size=1)

# merge both tables
fg_tile_table = fg_tile_upper_table

with open(src_dir / "graphics.68k","w") as f:
    f.write(generated_message)
    f.write("\t.global\tfg_character_table\n")
    f.write("\t.global\tbg_character_table\n")
    f.write("\t.global\tshared_bob_table\n")
    f.write("\t.global\tend_tables\n")
    f.write("fg_character_table:\n")

    offset = dump_tile_layer(fg_tile_table,"fg_")


    for k,v in tile_plane_cache.items():
        f.write(f"fg_tile_plane_{v:02d}:")
        dump_asm_bytes(k,f)

    f.write("bg_character_table:\n")
    dump_tile_layer(bg_tile_table,"bg_")
    for k,v in bg_tile_plane_cache.items():
        f.write(f"bg_tile_plane_{v:02d}:")
        dump_asm_bytes(k,f)

    f.write("shared_bob_table:\n")
    dump_bob_layer(sprite_table,f)




